### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by tdoolaege** [myTselection/telenet_telemeter#50] opened 2024-10-03 18:16 UTC
Hi,
I had your tool for a while now. and it worked perfectly until about a week ago (i think).
for some reason i tried removing the hacs plugin and reinstalling it. But it resolved to nothing.
all i see it wifi button.

i always used my old login txxxxxx, but now it doesn't work anymore. i have tried with my telenet login but still nothing.
Pic below shows with every possible login i knew i had for telenet. (cannot reset my passw for txxxxxx)

![image](https://github.com/user-attachments/assets/742cbddd-e1b0-4626-af55-f8bb9393d1fe)

when i check the logging i see 3 errors
![image](https://github.com/user-attachments/assets/c5da47de-2adc-447c-aafb-d433f373dd2f)

this is what the loggings are showing.
```
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:361
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 2 oktober 2024 om 22:03:25 (9 gebeurtenissen)
Laatst gelogd: 20:07:42

Error while setting up telenet_telemeter platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/telenet_telemeter/utils.py", line 81, in callTelenet
    assert response.status_code == expectedStatusCode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 119, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 52, in dry_setup
    await data_internet._forced_update()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 166, in _forced_update
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/sensor.py", line 166, in <lambda>
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/utils.py", line 119, in login
    self.callTelenet("https://api.prd.telenet.be/ocapi/oauth/userdetails","login")
  File "/config/custom_components/telenet_telemeter/utils.py", line 103, in callTelenet
    assert response.status_code == expectedStatusCode
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
the middle error show below
![image](https://github.com/user-attachments/assets/a8abfb80-9573-4114-abb7-0f42c7d4c711)

and the last error showing:
```
Logger: homeassistant.helpers.entity
Bron: helpers/entity.py:942
Eerst voorgekomen: 2 oktober 2024 om 22:03:55 (3 gebeurtenissen)
Laatst gelogd: 20:08:12

Update for switch.telenet_telemeter_wifi fails
Traceback (most recent call last):
  File "/config/custom_components/telenet_telemeter/utils.py", line 81, in callTelenet
    assert response.status_code == expectedStatusCode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 210, in async_update
    await self._data.update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 167, in update
    await self._update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 160, in _update
    await self.force_update()
  File "/config/custom_components/telenet_telemeter/switch.py", line 123, in force_update
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/switch.py", line 123, in <lambda>
    await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/utils.py", line 119, in login
    self.callTelenet("https://api.prd.telenet.be/ocapi/oauth/userdetails","login")
  File "/config/custom_components/telenet_telemeter/utils.py", line 103, in callTelenet
    assert response.status_code == expectedStatusCode
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```  
probably its stupidity on my behalf ... hope you can help

**Comment by KingT** [comment] 2024-10-04 05:18
Same issue here.
After removing and adding the hub again I only see the option to disable/enable my wifi again on the router.

**Comment by myTselection** [comment] 2024-10-04 06:17
The username to use should be the same of the one you use to login on 'MijnTelenet' website. The old txxxx login aren't supported any longer, this should probably be your email adres. Best to first test on the standard website.

The release 1.7.x were related to internet bundle fixes. I'll check further later today if I can fix something still, the issue is that I don't have a bundle myself, so I can't validate all cases...
R1.7.1 is showing all sensors again for me. 
If you'd see some issues, it would be very helpful if debug could be enabled and logs shared?

**Comment by tdoolaege** [comment] 2024-10-05 17:42
```

``` Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:361
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 19:41:02 (1 gebeurtenissen)
Laatst gelogd: 19:41:02

Error while setting up telenet_telemeter platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 119, in async_setup_entry
    await dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/telenet_telemeter/sensor.py", line 52, in dry_setup
    await data_internet._forced_update()
  File "/config/custom_components/telenet_telemeter/sensor.py", line 199, in _forced_update
    dailyUsage = await self._hass.async_add_executor_job(lambda: self._session.productDailyUsage("internet", productIdentifier, startDate,endDate))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/sensor.py", line 199, in <lambda>
    dailyUsage = await self._hass.async_add_executor_job(lambda: self._session.productDailyUsage("internet", productIdentifier, startDate,endDate))
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/telenet_telemeter/utils.py", line 186, in productDailyUsage
    return response.json()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tdoolaege** [comment] 2024-10-05 17:48
[home-assistant_telenet_telemeter_2024-10-05T17-44-30.821Z.log](https://github.com/user-attachments/files/17266975/home-assistant_telenet_telemeter_2024-10-05T17-44-30.821Z.log)

certain of correct login, cause i use the credentials through bitwaren copy/paste. i use a pack of "ONEup for 1 "
maybe that could be it..? 

still thnx for making this though really appreciate the work you put into it.

**Comment by jorisrymenants** [comment] 2024-10-07 10:56
Sam error in log as [tdoolaege](https://github.com/tdoolaege)

**Comment by myTselection** [comment] 2024-10-07 20:02
thx for reporting! I found some family member with a bundle subscription so I could test and fix these flows now myself, 
I hope it's now all fixed as of R1.8.1.

**Closed by myTselection** 2024-10-07 20:02 UTC

**Comment by KingT** [comment] 2024-10-08 15:43
Great work!
Works like a charm now 👍
Thanks!

**Comment by tdoolaege** [comment] 2024-10-08 16:09
I just made a mistake by changing my subscription. As it was cheaper 🤪. Its stil in activation mode will update..but it sounds promissing great work
